FileVersion = 1
Projects = {Example = {Path = "Example"}, glfw-beef = "*", Bgfx = {Path = "."}}

[Workspace]
StartupProject = "Example"

[Configs.Test.Win32]
ConfigSelections = {Example = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {Example = {Config = "Debug"}}
