FileVersion = 1
Projects = {Bgfx = {Path = "."}, Example = {Path = "Example"}, glfw-beef = {Path = "Example/Libs/glfw-beef"}}
Locked = ["glfw-beef"]

[Workspace]
StartupProject = "Example"

[Configs.Test.Win32]
ConfigSelections = {Bgfx = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {Bgfx = {Config = "Debug"}}
